-- CreateTable
CREATE TABLE "Character" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "element" TEXT NOT NULL,
    "attackType" TEXT NOT NULL,
    "job" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "urlSafeName" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "statsId" TEXT,

    CONSTRAINT "Character_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Stats" (
    "id" TEXT NOT NULL,
    "power" INTEGER NOT NULL DEFAULT 0,
    "ATK" INTEGER NOT NULL DEFAULT 0,
    "HP" INTEGER NOT NULL DEFAULT 0,
    "DEF" INTEGER NOT NULL DEFAULT 0,
    "CRIT" INTEGER NOT NULL DEFAULT 0,
    "HIT" INTEGER NOT NULL DEFAULT 0,
    "FLEE" INTEGER NOT NULL DEFAULT 0,
    "SPD" INTEGER NOT NULL DEFAULT 0,
    "REG" INTEGER NOT NULL DEFAULT 0,
    "MR" INTEGER NOT NULL DEFAULT 0,
    "PR" INTEGER NOT NULL DEFAULT 0,
    "LL" INTEGER NOT NULL DEFAULT 0,
    "CDR" INTEGER NOT NULL DEFAULT 0,
    "CDA" INTEGER NOT NULL DEFAULT 0,
    "MP" INTEGER NOT NULL DEFAULT 0,
    "PP" INTEGER NOT NULL DEFAULT 0,
    "CBR" INTEGER NOT NULL DEFAULT 0,
    "IS" INTEGER NOT NULL DEFAULT 0,
    "HEAL" INTEGER NOT NULL DEFAULT 0,
    "TY" INTEGER NOT NULL DEFAULT 0,
    "RH" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "Stats_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Character_name_key" ON "Character"("name");

-- CreateIndex
CREATE UNIQUE INDEX "Character_urlSafeName_key" ON "Character"("urlSafeName");

-- CreateIndex
CREATE UNIQUE INDEX "Character_statsId_key" ON "Character"("statsId");

-- AddForeignKey
ALTER TABLE "Character" ADD CONSTRAINT "Character_statsId_fkey" FOREIGN KEY ("statsId") REFERENCES "Stats"("id") ON DELETE SET NULL ON UPDATE CASCADE;
